# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AthyrAgent < Formula
  desc "YAML-driven agent runner for Athyr"
  homepage "https://athyr.tech"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/athyr-tech/athyr-agent/releases/download/v0.1.1/athyr-agent_0.1.1_darwin_amd64.tar.gz"
      sha256 "1b78f47b0a1064fc601d9008d2e0e51444f2c242592b75e1df0abeadc32185ca"

      def install
        bin.install "athyr-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/athyr-tech/athyr-agent/releases/download/v0.1.1/athyr-agent_0.1.1_darwin_arm64.tar.gz"
      sha256 "edc75dd22eaa14182d18560c51d19530c33b777ba19394d1990da4a5bd2658ad"

      def install
        bin.install "athyr-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/athyr-tech/athyr-agent/releases/download/v0.1.1/athyr-agent_0.1.1_linux_amd64.tar.gz"
      sha256 "5851c6b9b832bef0275c9485daa3d267aa77bd644522beba16e96d429a82f834"
      def install
        bin.install "athyr-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/athyr-tech/athyr-agent/releases/download/v0.1.1/athyr-agent_0.1.1_linux_arm64.tar.gz"
      sha256 "01bcfb358259b3c1c3b87b60bac3dd40a8ffc4eff452d61cc95e91d6b4756892"
      def install
        bin.install "athyr-agent"
      end
    end
  end

  test do
    system bin/"athyr-agent", "version"
  end
end
