# Athyr Homebrew Formula
# Auto-generated by make update-homebrew

class Athyr < Formula
  desc "AI agent orchestration platform"
  homepage "https://athyr.tech"
  version "0.1.6"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/athyr-tech/athyr-bin/releases/download/v0.1.6/athyr_0.1.6_darwin_arm64.tar.gz"
      sha256 "54be3e1893fb41f12206d917cc4c0ce7d6df869c024b7401a24db1f5e220a2fd"
    end
    on_intel do
      url "https://github.com/athyr-tech/athyr-bin/releases/download/v0.1.6/athyr_0.1.6_darwin_amd64.tar.gz"
      sha256 "cc52779f9fefe107fe2a3ce0d58077268a649b7f96dd947166ff05ee1ed380d6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/athyr-tech/athyr-bin/releases/download/v0.1.6/athyr_0.1.6_linux_arm64.tar.gz"
      sha256 "7020a55b1a55e87bd792e90a47dd9eca1c165adafabeb5254b54c9bde4dc6c82"
    end
    on_intel do
      url "https://github.com/athyr-tech/athyr-bin/releases/download/v0.1.6/athyr_0.1.6_linux_amd64.tar.gz"
      sha256 "a01ae02b20de2455035a93c32783e6b0a5bb8a2a4cea411e718795f5e947bcfc"
    end
  end

  def install
    bin.install "athyr"
  end

  test do
    system "#{bin}/athyr", "--version"
  end
end
