# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AthyrAgent < Formula
  desc "YAML-driven agent runner for Athyr"
  homepage "https://athyr.tech"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/athyr-tech/athyr-agent/releases/download/v0.1.1/athyr-agent_0.1.1_darwin_amd64.tar.gz"
      sha256 "1053e4ce3391a23c72b34af7a89fa04f4f6e80fa05f4dd6b5fa251231e844466"

      def install
        bin.install "athyr-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/athyr-tech/athyr-agent/releases/download/v0.1.1/athyr-agent_0.1.1_darwin_arm64.tar.gz"
      sha256 "2f3d41bc12d22ec9dca279d82c975cdcf1e7d2cb9f5b5d50af882816fe11a423"

      def install
        bin.install "athyr-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/athyr-tech/athyr-agent/releases/download/v0.1.1/athyr-agent_0.1.1_linux_amd64.tar.gz"
      sha256 "3fa66967008c00bb28af422402d001516a27bb39e63a8d56b3e15883c2e23381"
      def install
        bin.install "athyr-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/athyr-tech/athyr-agent/releases/download/v0.1.1/athyr-agent_0.1.1_linux_arm64.tar.gz"
      sha256 "121ba2bb8e93b4ad18ac36810ef60be4367503392941fc642950c6c532aab807"
      def install
        bin.install "athyr-agent"
      end
    end
  end

  test do
    system bin/"athyr-agent", "version"
  end
end
