# Athyr Homebrew Formula
# Auto-generated by make update-homebrew

class Athyr < Formula
  desc "AI agent orchestration platform"
  homepage "https://athyr.tech"
  version "0.1.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/athyr-tech/athyr-bin/releases/download/v0.1.5/athyr_0.1.5_darwin_arm64.tar.gz"
      sha256 "e34228c15e658c14b340fc7d571201bb13fe1fbd2fbbe3a8313a5c08bc4f16b8"
    end
    on_intel do
      url "https://github.com/athyr-tech/athyr-bin/releases/download/v0.1.5/athyr_0.1.5_darwin_amd64.tar.gz"
      sha256 "ef3de02de36e880d355514c407d20996df8d13cb64c229189e07c070555f2ca2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/athyr-tech/athyr-bin/releases/download/v0.1.5/athyr_0.1.5_linux_arm64.tar.gz"
      sha256 "5cf1ea5f16d47784ca5aa405ada02c88ea753eaf8b17a33068428580f6e1a404"
    end
    on_intel do
      url "https://github.com/athyr-tech/athyr-bin/releases/download/v0.1.5/athyr_0.1.5_linux_amd64.tar.gz"
      sha256 "2fee7fc9a1bc1f828417f2ebe9dee5ca60602616134fa728d48b2ffcb8f2fa53"
    end
  end

  def install
    bin.install "athyr"
  end

  test do
    system "#{bin}/athyr", "--version"
  end
end
