# Athyr Homebrew Formula
# Auto-generated by make update-homebrew

class Athyr < Formula
  desc "AI agent orchestration platform"
  homepage "https://athyr.tech"
  version "0.1.10"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/athyr-tech/athyr-bin/releases/download/v0.1.10/athyr_0.1.10_darwin_arm64.tar.gz"
      sha256 "fdbc99bc91983c23dffc58bf50194b2894246af435bad163563d1dd026ed15c6"
    end
    on_intel do
      url "https://github.com/athyr-tech/athyr-bin/releases/download/v0.1.10/athyr_0.1.10_darwin_amd64.tar.gz"
      sha256 "6571e74174c25833414b1bcb13ed2ca049a8c189553f1372883a65093985efbd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/athyr-tech/athyr-bin/releases/download/v0.1.10/athyr_0.1.10_linux_arm64.tar.gz"
      sha256 "e135a1c1d764ae1adc6d99330080ef75514c4d685733358ba2fa89b766f1bb91"
    end
    on_intel do
      url "https://github.com/athyr-tech/athyr-bin/releases/download/v0.1.10/athyr_0.1.10_linux_amd64.tar.gz"
      sha256 "3491b6f521dafabde089fe0921b647fabedb83e18c879fa0a08105dcdcaf9988"
    end
  end

  def install
    bin.install "athyr"
  end

  test do
    system "#{bin}/athyr", "--version"
  end
end
